In [2]:
import numpy as np


In [3]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr=np.array(list)

print(arr *4)

[ 80 108  36  48 124  68  16 200 156 140]


In [4]:
print(np.mean(arr))

24.4


In [5]:
print(np.median(arr))

23.5


In [6]:
print(np.std(arr))

13.828955130450023


In [9]:
print(np.argmin(arr))
print(np.argmax(arr))

6
7


In [13]:
min_index = np.argmin(arr)  
max_index = np.argmax(arr)
print(f" index {min_index} is: {arr[min_index]}")
print(f"index {max_index} is: {arr[max_index]}")

 index 6 is: 4
index 7 is: 50


In [14]:
print(np.min(arr))
print(np.max(arr))
# Do they match those from the previous step? yes, they do.

4
50


In [16]:
# Create a new array with only values greater than 20 with Boolean indexing. Print it.
great = arr>20
values = arr[great]
print(values)

[27 31 50 39 35]


In [ ]:
# 2D NumPy Arrays

In [18]:
matrix = [
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
]

print (np.shape(matrix))
# 4 columns, 3 rows

# Print the third column.

(3, 4)


In [28]:
mtrx = np.array(matrix)
third_column = mtrx[:,2]
print(third_column)

[17 14 19]


In [30]:
second = mtrx[:,1]
print(second) 
 

[12 21 13]


In [31]:
print(mtrx *2)

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [35]:
print (np.mean(mtrx[:,0]))
print (np.mean(second))
print (np.mean(third_column))
print (np.mean(mtrx, axis=0))


6.333333333333333
15.333333333333334
16.666666666666668
[ 6.33333333 15.33333333 16.66666667  7.66666667]


In [36]:
# Find and print the overall mean of the array.
print (np.mean(mtrx))

11.5


In [43]:
# Find the max value in each row and the min value in each column.
max_val = np.max(mtrx, axis=1)
print(f"the max values in each row are:", max_val) 
min_val = np.min(mtrx, axis=0)
print(f"the min values in each column are:", min_val)

the max values in each row are: [17 21 19]
the min values in each column are: [ 5 12 14  3]


In [50]:
flat= mtrx.flatten()
print (flat)
print (f"shape is",np.shape(flat))

[ 5 12 17  9  8 21 14  3  6 13 19 11]
shape is (12,)


In [55]:
flat_min=np.argmin(flat)
flat_max=np.argmax(flat)
print (f"flat min index",flat_min)
print (f"flat max index",flat_max)

flat min index 7
flat max index 5


In [60]:
num_min = np.unravel_index(flat_min, mtrx.shape)
num_max=np.unravel_index(flat_max, mtrx.shape)
print("Min coordinates (row, col):", num_min)
print("Max coordinates (row, col):", num_max)

Min coordinates (row, col): (np.int64(1), np.int64(3))
Max coordinates (row, col): (np.int64(1), np.int64(1))


In [61]:
greater = mtrx>15
than_15 = mtrx[greater]
print(than_15)

[17 21 19]


In [66]:
sorted = np.sort(mtrx,axis=1)
print( sorted)

[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [ ]:
# 4
# prime number

In [ ]:
arr = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])

In [68]:
def is_prime(n):


In [ ]:
# 5

In [70]:
def creating8x8_zeros():
    return np.zeros((8,8))
zer_array=creating8x8_zeros()
print(zer_array)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [76]:
grid = np.zeros((8, 8), dtype=int)
grid[0::2, 0::2] = 1
print(grid)

[[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]


In [96]:
grid = np.zeros((8, 8), dtype=int) 
grid[0::2, 0::2] = 1
print(grid)

[[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]


In [94]:
def checkerboard():
    grid = np.zeros((8, 8), dtype=int)
    grid[0::2, 0::2] = 1
    grid[1::2, 1::2] = 1 
    return grid

print(checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [98]:
def reverse_checkerboard():
    grid = np.zeros((8, 8), dtype=int)
    grid[0::2, 1::2] = 1
    grid[1::2, 0::2] = 1
    return grid
print(reverse_checkerboard())

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# 6

In [107]:
def expansion(arr, n):
    spac = ' ' * n
    return np.array([spac.join(s) for s in arr])
universe = np.array(['galaxy', 'clusters'])
print(expansion(universe,1))
print(expansion(universe, 2))

['g a l a x y' 'c l u s t e r s']
['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']


In [ ]:
# 7


In [109]:
def second_brightest(stars):

    sortedd = np.sort(stars, axis=1)
    
#     np.random.seed(123):
    
# for stars = np.random.randint(500, 2000, (5, 5)):
# array([[1123, 1456, 1789, 1324, 1876],
# [1567, 1987, 1678, 1405, 1589],
# [1345, 1654, 1523, 1109, 1923],
# [1298, 1890, 1367, 1784, 1432],
# [1823, 1756, 1489, 1672, 1550]])
# def secondDimmest(stars):
# array([1789, 1678, 1654, 1784, 1756])